services:

  jenkins-blueocean:
    build:
       ./Jenkins
    container_name: jenkins-blueocean
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JAVA_OPTS: "-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins-data-mock:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - .:/home
    restart: on-failure
    depends_on:
        - jenkins-docker

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data-mock:/var/jenkins_home
      - .:/home
    ports:
      - "2376:2376"
      - "5000:5000"
    command: --storage-driver overlay2

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - jenkins
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: on-failure

  nginxwebsvr:
      image: nginx:alpine
      container_name: nginxwebsvr
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "80:80"
      networks:
        - jenkins

  git-server:
    build:
        context: ./Git/
    restart: always
    ports:
        - "3000:3000"
    networks:
        - jenkins

volumes:
    jenkins-data-mock:
        name: jenkins-data-mock
    jenkins-docker-certs:
        name: jenkins-docker-certs
    sonarqube_data:
        name: sonarqube_data
    sonarqube_extensions:
        name: qube_extensions
    sonarqube_logs:
        name: sonarqube_logs

networks:
  jenkins:

